env:

dev:
  adapter: SQLite
  database:
  host: db/dev.sqlite
  username:
  password:
  port:
  config:

prod:
  adapter:
  database:
  host:
  username:
  password:
  port:
  config:

test:
  adapter:
  database:
  host:
  username:
  password:
  port:
  config: 
